### ISSUE TITLE
Creation of new organizations is broken

### ISSUE THREAD

**Issue by robvanmieghem** [itsyouonline/identityserver#53]
```
angular.js:13550 TypeError: Cannot read property 'split' of undefined
    at getChildOrganizations (https://dev.itsyou.online:8443/components/organization/controller.js:459:48)
    at activate (https://dev.itsyou.online:8443/components/organization/controller.js:25:41)
    at new OrganizationController (https://dev.itsyou.online:8443/components/organization/controller.js:22:9)
    at Object.instantiate (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.js:4680:14)
```

**Comment by robvanmieghem** [comment]
https://github.com/itsyouonline/identityserver/pull/54
