### ISSUE TITLE
panic: please specify '--import-path' or set '--dir' under your GOPATH

### ISSUE THREAD

**Issue by rainmanh** [itsyouonline/identityserver#648]
Using golang 1.9.1
Ubuntu 16.04 X86
Building from Master

```
go generate

panic: please specify '--import-path' or set '--dir' under your GOPATH

goroutine 1 [running]:
github.com/Jumpscale/go-raml/codegen/golang.setRootImportPath(0x0, 0x0, 0x7ffc09df8819, 0x17, 0x0, 0x0)
	/root/work/src/github.com/Jumpscale/go-raml/codegen/golang/util.go:35 +0x2cb
github.com/Jumpscale/go-raml/codegen/golang.NewClient(0xc4200a8500, 0x7ffc09df886b, 0xc, 0x0, 0x0, 0x7ffc09df8819, 0x17, 0xc420334160, 0x1, 0x1, ...)
	/root/work/src/github.com/Jumpscale/go-raml/codegen/golang/client.go:39 +0xb1
github.com/Jumpscale/go-raml/codegen.GenerateClient(0xc4200a8500, 0x7ffc09df8819, 0x17, 0x7ffc09df886b, 0xc, 0x7ffc09df8810, 0x2, 0x0, 0x0, 0x86a104, ...)
	/root/work/src/github.com/Jumpscale/go-raml/codegen/client.go:15 +0x2ea
github.com/Jumpscale/go-raml/commands.(*ClientCommand).Execute(0xc36740, 0xc4200ab560, 0x868d8c)
	/root/work/src/github.com/Jumpscale/go-raml/commands/client.go:38 +0x210
main.main.func3(0xc4200ab560)
	/root/work/src/github.com/Jumpscale/go-raml/main.go:166 +0x2d
github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli.Command.Run(0x869579, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x877ed4, 0x28, 0x0, ...)
	/root/work/src/github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli/command.go:137 +0x7f2
github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli.(*App).Run(0xc4200ab320, 0xc4200100a0, 0xa, 0xa, 0x0, 0x0)
	/root/work/src/github.com/Jumpscale/go-raml/vendor/github.com/codegangsta/cli/app.go:176 +0x8c1
main.main()
	/root/work/src/github.com/Jumpscale/go-raml/main.go:256 +0x1792
generate.go:12: running "go-raml": exit status 2
```

**Comment by rainmanh** [comment]
Issue sorted when following the example given in the Dockerfile .

probably documentation should be improved a bit more...

**Comment by svs1370** [comment]
Could you please provide more info here on how to solve this issue and close the issue eventually?
