### ISSUE TITLE
Can't add a new validated phone number on authorize page

### ISSUE THREAD

**Issue by lucasvanhalst** [itsyouonline/identityserver#694]
On staging, pressing 'Create new' in the validated phone number dropdown does nothing on the authorize page
pressing Authorize triggers this error

```
"TypeError: Cannot read property 'phonenumber' of undefined
                at https://staging.itsyou.online/components/user/authorizeController.js:380:71
                at Object.forEach (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:325:20)
                at https://staging.itsyou.online/components/user/authorizeController.js:375:33
                at processQueue (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:16606:28)
                at https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:16622:27
                at Scope.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:17913:28)
                at Scope.$digest (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:17727:31)
                at Scope.$apply (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:18021:24)
                at done (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:12002:47)
                at completeRequest (https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js:12211:7)", source: https://ajax.googleapis.com/ajax/libs/angularjs/1.5.9/angular.js (14110)
```

**Comment by ahmedelsayed-93** [comment]
### Version
staging server 
v0.9.16-117-g2b2fb7a
